# Generated by Django 5.1 on 2024-08-31 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_entry_camera', models.BooleanField(default=False)),
                ('level', models.IntegerField(choices=[(1, 'Full Access'), (2, 'Limited Access'), (3, 'Guest')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_plate', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('nationalCode', models.CharField(max_length=10, unique=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('career', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camera')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.carowner'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('isAllowed', models.BooleanField(default=True)),
                ('level', models.IntegerField(choices=[(1, 'Full Access'), (2, 'Limited Access'), (3, 'Guest')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.car')),
            ],
        ),
    ]
