# Generated by Django 5.1 on 2024-09-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_car_color_alter_car_license_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='isAllowed',
            new_name='is_allowed',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
