# Generated by Django 5.1 on 2024-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_enddate_permission_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateField(),
        ),
    ]
